apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cp4i-mq-
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  pipelineRef:
    name: cp4i-mq
  serviceAccountName: pipeline
  timeout: 6h0m0s
