apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  labels:
    app.kubernetes.io/instance: bootstrap
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: 'https://github.com/cloud-native-toolkit/deployer-cp4i.git'
      targetRevision: main
      path: 2022.4/pipelines
    #
    # NOTE: MQ pipelines don't exist yet, this is food for thought on how
    #       we can template capabilities deployment
    #
    # - repoURL: 'https://github.com/cloud-native-toolkit/deployer-cp4i.git'
    #   targetRevision: main
    #   path: 2022.4/pipelines/mq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true