apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployer-cp4i
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: 'https://github.com/airazabal/dp-pipeline.git'
      targetRevision: main
      path: 2022.4/pipelines/platform-ui
    # - repoURL: 'https://github.com/cloud-native-toolkit/deployer-cp4i.git'
    #   targetRevision: main
    #   path: 2022.4/pipelines/mq
    # - repoURL: 'https://github.com/cloud-native-toolkit/deployer-cp4i.git'
    #   targetRevision: main
    #   path: 2022.4/pipelines/api-connect
    # - repoURL: 'https://github.com/cloud-native-toolkit/deployer-cp4i.git'
    #   targetRevision: main
    #   path: 2022.4/pipelines/app-connect
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true